### ISSUE TITLE
PlatON Network Community Development Invitation

### ISSUE THREAD

**Issue by biganxin** [jarys/ztrezor#1]
Sorry to interrupt you.

We are looking for developer ambassadors to participate in efforts such as Platon/Alaya network building and developer community training and education.
If you are interested please establish contact with me.

Contact：
Discord：https://discord.gg/jAjFzJ3Cff （@Boney2）
Dev-Telegram：https://t.me/joinchat/LhO63AsZ_iozZGNl （@@Boneybi）

**Comment by luckytokidoki** [comment]
Dude, what kind of marketing strategy is this? Spamming people's issue tracker on GitHub? Huge red flag. Thank you for making sure I can just ignore your project.

@jarys I think you need to close this issue as it's irrelevant to your project.

**Comment by biganxin** [comment]
I am a volunteer in the community and do not represent the way the project is implemented
I apologize for making you uncomfortable in this way, I will close it
